<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        <?php 
        try { echo App\Core\I18n::get('hello_world'); }
        catch (\Exception $e) { echo $e->getMessage(); }
        ?>
        |
        <?= $viewData['title'] ?>

    </title>
    <link rel="stylesheet" type="text/css" 
        href="<?=$this->asset('css/style.css')?>" />
</head>